# Generated by Django 2.2.5 on 2020-04-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20200418_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.ManyToManyField(to='resource.Url'),
        ),
    ]
