# Generated by Django 3.0.5 on 2020-04-18 23:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_auto_20200419_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), null=True, size=None),
        ),
    ]
