# Generated by Django 3.0.5 on 2020-04-18 23:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_post_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, size=None),
        ),
    ]
