# Generated by Django 3.0.5 on 2020-04-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0010_auto_20200419_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
