# Generated by Django 3.0.5 on 2020-04-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0011_post_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='confirmed',
        ),
    ]
