# Generated by Django 3.0.5 on 2020-04-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0012_remove_post_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
