# Generated by Django 3.0.5 on 2020-04-19 15:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0015_auto_20200419_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.Post'),
        ),
        migrations.AlterField(
            model_name='url',
            name='title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
    ]
