# Generated by Django 3.0.5 on 2020-04-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_auto_20200419_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Post'),
        ),
    ]
