# Generated by Django 3.0.5 on 2020-04-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0018_auto_20200419_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='post_id',
            new_name='post',
        ),
    ]
