# Generated by Django 3.0.5 on 2020-04-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0019_auto_20200419_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='post',
        ),
    ]
