# Generated by Django 3.0.5 on 2020-04-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0023_auto_20200419_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.Post'),
        ),
    ]
