# Generated by Django 3.0.5 on 2020-04-24 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0028_auto_20200424_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
