# Generated by Django 3.0.5 on 2020-04-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0029_auto_20200424_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-pk']},
        ),
    ]
