# Generated by Django 3.0.5 on 2020-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0033_auto_20200425_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
