# Generated by Django 3.0.5 on 2020-04-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0034_resource_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
