# Generated by Django 3.0.5 on 2020-04-19 19:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freecourses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freecourses.Course')),
            ],
        ),
    ]
