# Generated by Django 3.0.5 on 2020-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecourses', '0002_urlcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='urlcourse',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='course',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
