# Generated by Django 3.0.5 on 2020-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecourses', '0003_auto_20200422_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
